### ISSUE TITLE
PackageManager Permissions

### ISSUE THREAD

**Issue by loneObserver1** [Faiza-Farooqui/cnic_scanner#3]
`/Users/thibault/Documents/dev/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.3.0/android/src/main/java/com/baseflow/permissionhandler/ServiceManager.java:75: warning: [deprecation] queryIntentActivities(Intent,int) in PackageManager has been deprecated
            List<ResolveInfo> callAppsList = pm.queryIntentActivities(callIntent, 0);
                                               ^
error: warnings found and -Werror specified
/Users/thibault/Documents/dev/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.3.0/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:317: warning: [deprecation] getPackageInfo(String,int) in PackageManager has been deprecated
                    .getPackageInfo(context.getPackageName(), PackageManager.GET_PERMISSIONS);`

I've got this error when I install package on my project. Gradle version build target 33
I try to update packages and update PackageManager but nothing append else 

This error is call on PermissionsUtils
`PackageInfo info = context
                    .getPackageManager()
                    .getPackageInfo(context.getPackageName(), PackageManager.GET_PERMISSIONS);`

Someone can help me

**Comment by Faiza-Farooqui** [comment]
it has nothing to do with package. You have to do some changes in your project's manifest. I am attaching a link, hope you find it useful. 

https://stackoverflow.com/questions/62345805/namenotfoundexception-when-calling-getpackageinfo-on-android-11

hope it's help
