### ISSUE TITLE
image does not taken 

### ISSUE THREAD

**Issue by SaqeelAhmad** [Faiza-Farooqui/cnic_scanner#7]

**Comment by SaqeelAhmad** [comment]
Camera does not open, and gallery does not open

**Comment by Faiza-Farooqui** [comment]
it is not producing at my end, please attach screenshot of the error you're facing or any other useful information.

**Comment by elvis-kaile** [comment]
Hello, 
I have the same problem but at my side the camera is open. But when I take the photo and submit it, the camera is open again.  

please, can you help me ?

**Comment by Faiza-Farooqui** [comment]
Thank you for your email. I will check that tomorrow and resolve the issue.
